"""Painéis por projeto: consumo, armazenamento seletivo e comparação de visões."""
STYLE=r'''
.insights-controls{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin:16px 0}.insights-controls label{font-size:12px;margin:0 0 4px}.insights-controls select{max-width:100%;min-height:40px}.insights-table-wrap{max-height:340px;overflow:auto;margin:16px 0}.insights-table{width:100%;border-collapse:collapse;font-size:13px}.insights-table th,.insights-table td{text-align:left;vertical-align:top;padding:10px 9px;border-bottom:1px solid var(--border);overflow-wrap:anywhere}.insights-table th{color:var(--muted);font-weight:600}.insights-table td:first-child,.insights-table th:first-child{padding-left:0}.insights-table td button{font-size:12px;min-height:30px;padding:4px 8px}.insights-note{color:var(--muted);font-size:13px;overflow-wrap:anywhere}.insights-summary{display:grid;grid-template-columns:1fr 1fr;gap:0 20px;margin:14px 0}.insights-summary div{padding:10px 0;border-top:1px solid var(--border)}.insights-summary small{display:block}.insights-summary strong{font-size:15px}.cleanup-preview{border:1px solid var(--border);border-radius:8px;padding:16px;margin:16px 0}.comparison-diff{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.65 Consolas,monospace;max-height:430px;overflow:auto}.comparison-diff .added{color:var(--good)}.comparison-diff .removed{color:var(--bad)}.comparison-item{width:100%;text-align:left;margin:4px 0}.insights-note:empty{display:none}.insights-panel select{min-width:0}.insights-views{display:grid;grid-template-columns:1fr 1fr;gap:16px}.insights-views select{width:100%}
@media(max-width:700px){.insights-summary,.insights-views{grid-template-columns:1fr}.insights-table{min-width:490px}.insights-controls>div{max-width:100%}}
'''
HTML=r'''
<details class="insights-panel" id="usage-panel"><summary>Usage and reuse by project and view</summary>
<div class="insights-controls"><div><label for="usage-days">Period</label><select id="usage-days"><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option><option value="366">1 year</option></select></div><div><label for="usage-view">View</label><select id="usage-view"><option value="">All</option></select></div><button id="usage-load">Refresh usage</button></div><p id="usage-message" class="insights-note">Local counts and usage reported by the gateway. No query text is saved in this telemetry.</p><div id="usage-summary" class="insights-summary"></div><div id="usage-table" class="insights-table-wrap"></div><div id="usage-indexing" class="insights-table-wrap"></div></details>
<details class="insights-panel" id="storage-panel"><summary>Disk space and view cleanup</summary><div class="insights-controls"><button id="storage-load">Refresh inventory</button></div><p class="insights-note">The active view and pinned views are protected. Cleanup is manual and removes only Smart Tool indexes and cache.</p><div id="storage-summary" class="insights-summary"></div><div id="storage-table" class="insights-table-wrap"></div><label class="check-label"><input id="cleanup-cache" type="checkbox" checked>Also clear vectors no longer used by the stored generations</label><div class="actions"><button id="cleanup-preview" disabled>Preview selected cleanup</button></div><div id="cleanup-plan" class="cleanup-preview" hidden></div><button id="cleanup-apply" class="danger" hidden>Confirm removal of this preview</button><p id="storage-message" class="insights-note"></p></details>
<details class="insights-panel" id="compare-panel"><summary>Compare two stored views</summary><p class="insights-note">The comparison uses the index content, with no checkout and no new embeddings. Scope differences can also show up as added or removed files.</p><button id="compare-load-views">Load views</button><div class="insights-views"><div><label for="compare-left">View A · base</label><select id="compare-left"></select></div><div><label for="compare-right">View B · compare with A</label><select id="compare-right"></select></div></div><label class="check-label"><input id="compare-relations" type="checkbox" checked>Also compare resolved references and static calls</label><div class="actions"><button id="compare-run" disabled>Compare A → B</button></div><p id="compare-message" class="insights-note"></p><div id="compare-summary" class="insights-summary"></div><div id="compare-files" class="insights-table-wrap"></div><div id="compare-graph"></div><h3 id="compare-file-title"></h3><pre id="compare-diff" class="comparison-diff"></pre></details>
'''
SCRIPT=r'''
window.SmartInsights=(()=>{
 const $i=id=>document.getElementById(id);let sequence=0,storage=null,plan=null,comparison=null,compareRequest=0,diffRequest=0;
 const count=n=>Number(n||0).toLocaleString('en-US'),size=n=>n>=1048576?(n/1048576).toLocaleString('en-US',{maximumFractionDigits:2})+' MiB':(n/1024).toLocaleString('en-US',{maximumFractionDigits:1})+' KiB';
 const phaseNames={index_embedding:'Indexing',query_embedding:'Query',embedding_probe:'Model check',scope:'Scope',rerank:'Rerank',other:'Other step'};
 function summary(host,rows){host.innerHTML=rows.map(([title,value,note])=>`<div><small>${esc(title)}</small><strong>${esc(value)}</strong>${note?'<small>'+esc(note)+'</small>':''}</div>`).join('')}
 function table(headers,rows){return '<table class="insights-table"><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(value=>'<td>'+value+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
 async function run(button,task){const seq=sequence,key=selected;button.disabled=true;try{await task(key,()=>seq===sequence&&key===selected)}catch(e){if(seq===sequence)message(e.message,true)}finally{if(seq===sequence)button.disabled=false}}
 function clearPlan(){plan=null;$i('cleanup-plan').hidden=true;$i('cleanup-apply').hidden=true;$i('cleanup-preview').disabled=!document.querySelector('#storage-table input[data-storage]:checked')}
 function reset(){sequence++;storage=null;comparison=null;plan=null;for(const id of ['usage-summary','usage-table','usage-indexing','storage-summary','storage-table','storage-message','compare-summary','compare-files','compare-graph','compare-file-title','compare-diff','compare-message'])$i(id).replaceChildren();$i('usage-view').replaceChildren(new Option('All',''));$i('compare-left').replaceChildren();$i('compare-right').replaceChildren();$i('compare-run').disabled=true;clearPlan();for(const id of ['usage-load','storage-load','compare-load-views'])$i(id).disabled=false;$i('usage-message').textContent='Refresh the usage of this project. The telemetry stores only counts and metadata.'}
 async function loadUsage(key,valid){const requestedDays=$i('usage-days').value,requestedView=$i('usage-view').value;const data=await api({action:'usage',project_id:key,days:Number($i('usage-days').value),...($i('usage-view').value?{view_id:$i('usage-view').value}:{})});if(!valid()||requestedDays!==$i('usage-days').value||requestedView!==$i('usage-view').value)return;const t=data.totals,old=$i('usage-view').value,views=new Map();for(const row of [...data.daily,...data.indexing])views.set(row.view_id,row.view_label);if(!old)$i('usage-view').replaceChildren(new Option('All',''),...Array.from(views,([id,label])=>new Option(label||id,id)));summary($i('usage-summary'),[['Call attempts',count(t.attempts),count(t.errors)+' with errors'],['Reported tokens',t.token_reports?count((t.prompt_tokens||0)+(t.output_tokens||0)):'Not reported',count(t.token_reports)+' of '+count(t.attempts)+' calls with data'],['Cost reported by the gateway',t.reported_usd==null?'Not reported':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(t.reported_usd),count(t.price_reports)+' calls with a cost; not the full bill'],['Chunks sent / cache',count(data.indexing.reduce((s,r)=>s+r.embedded_chunks,0))+' / '+count(data.indexing.reduce((s,r)=>s+r.reused_chunks,0)),'Unchanged files are counted separately']]);$i('usage-message').textContent='Loaded period: '+data.days+' days (UTC). '+data.notes.join(' ');$i('usage-table').innerHTML=table(['Date UTC','View / step','Model','Attempts','Reported tokens','Measured characters'],data.daily.slice(0,200).map(r=>[esc(r.day),esc(r.view_label)+'<br>'+esc(phaseNames[r.purpose]||r.purpose),esc(r.model),count(r.attempts),r.token_reports?count(r.prompt_tokens+r.output_tokens):'Not reported',count(r.input_characters)]));$i('usage-indexing').innerHTML=table(['View','Indexing jobs','Chunks sent','Cache reuse','Unchanged files'],data.indexing.map(r=>[esc(r.view_label),count(r.jobs),count(r.embedded_chunks),count(r.reused_chunks),count(r.unchanged_files)]))}
 function renderStorage(data){storage=data;clearPlan();summary($i('storage-summary'),[['SQLite indexes',size(data.total_bytes)],['Vector cache',size(data.cache_bytes)],['Auxiliary generations',size(data.auxiliary_bytes)],['Stored views',count(data.views.length),'Active and pinned views are protected']]);$i('storage-table').innerHTML=table(['Clear','View','Space','Protection'],data.views.map(v=>[`<input type="checkbox" data-storage="${esc(v.storage_id)}" aria-label="Select ${esc(v.label)} for cleanup" ${v.protected?'disabled':''}>`,esc(v.label)+'<br><small>'+esc(v.commit?.slice(0,10)||'Commit not recorded')+'</small>',size(v.bytes),esc(v.protected_reason||'Can be selected')+`<br><button data-pin="${esc(v.storage_id)}" data-pinned="${v.pinned?'1':'0'}">${v.pinned?'Unpin':'Pin'}</button>`]));$i('storage-message').textContent=data.views.length?'Choose the old views and check the preview before removing.':'No stored views in this project.';clearPlan()}
 async function loadStorage(key,valid){const data=await api({action:'storage',project_id:key});if(valid())renderStorage(data)}
 $i('usage-load').onclick=()=>run($i('usage-load'),loadUsage);$i('usage-days').onchange=()=>run($i('usage-load'),loadUsage);$i('usage-view').onchange=()=>run($i('usage-load'),loadUsage);$i('storage-load').onclick=()=>run($i('storage-load'),loadStorage);
 $i('storage-table').onchange=clearPlan;$i('cleanup-cache').onchange=clearPlan;
 $i('storage-table').onclick=e=>{const button=e.target.closest('[data-pin]');if(button)run(button,async(key,valid)=>{const data=await api({action:'pin_view',project_id:key,storage_id:button.dataset.pin,pinned:button.dataset.pinned!=='1'});if(valid())renderStorage(data)})};
 $i('cleanup-preview').onclick=()=>run($i('cleanup-preview'),async(key,valid)=>{const ids=[...document.querySelectorAll('#storage-table input[data-storage]:checked')].map(n=>n.dataset.storage);const data=await api({action:'cleanup_preview',project_id:key,storage_ids:ids,clear_cache:$i('cleanup-cache').checked});if(!valid())return;plan=data;$i('cleanup-plan').hidden=false;$i('cleanup-plan').innerHTML='<h3>Removal preview</h3><ul>'+data.views.map(v=>'<li>'+esc(v.label)+'</li>').join('')+'</ul><p>'+size(data.index_bytes)+' in indexes; '+count(data.unused_vectors)+' unreferenced vectors ('+size(data.vector_bytes)+' of vector content).</p><p class="insights-note">'+esc(data.note||'The final cache size depends on SQLite compaction.')+'</p><p>The project files will be kept.</p>';$i('cleanup-apply').hidden=false});
 $i('cleanup-apply').onclick=()=>{if(!plan)return;if(!confirm('Remove the views in this preview: '+plan.views.map(v=>v.label).join(', ')+'? The project files will be kept.'))return;run($i('cleanup-apply'),async(key,valid)=>{const data=await api({action:'cleanup_commit',project_id:key,plan_id:plan.plan_id,confirm:true});if(!valid())return;renderStorage(data.storage);$i('storage-message').textContent=data.removed_views+' view(s) removed; '+data.removed_vectors+' vectors removed. '+data.warnings.join(' ');window.SmartMaps?.reset();await refresh()})};
 async function loadViews(key,valid){compareRequest++;diffRequest++;comparison=null;for(const id of ['compare-summary','compare-files','compare-graph','compare-file-title','compare-diff'])$i(id).replaceChildren();const data=await api({action:'storage',project_id:key});if(!valid())return;const options=data.views.map(v=>[v.storage_id,v.label+(v.current?' (active)':'')]);$i('compare-left').replaceChildren(...options.map(([id,label])=>new Option(label,id)));$i('compare-right').replaceChildren(...options.map(([id,label])=>new Option(label,id)));if(options.length>1)$i('compare-right').selectedIndex=1;$i('compare-run').disabled=options.length<2;$i('compare-message').textContent=options.length<2?'Two indexed views are needed. Run searches on the branches you want to store them.':'Differences will be shown from A to B.'}
 $i('compare-load-views').onclick=()=>run($i('compare-load-views'),loadViews);
 for(const id of ['compare-left','compare-right','compare-relations'])$i(id).onchange=()=>{compareRequest++;diffRequest++;comparison=null;for(const host of ['compare-summary','compare-files','compare-graph','compare-file-title','compare-diff'])$i(host).replaceChildren();$i('compare-run').disabled=!$i('compare-left').value||!$i('compare-right').value||$i('compare-left').value===$i('compare-right').value;$i('compare-message').textContent='Selection changed. Run the comparison from A to B.'};
 function fileButtons(data){const rows=[];for(const kind of ['added','removed','changed'])for(const path of data.files[kind])rows.push([kind==='added'?'Added in B':kind==='removed'?'Missing in B':'Changed',path]);for(const item of data.files.renamed)rows.push(['Rename detected',item.from+' → '+item.to]);return table(['Change','File'],rows.slice(0,1000).map(([kind,path])=>[esc(kind),kind==='Rename detected'?esc(path):`<button data-compare-file="${esc(path)}">${esc(path)}</button>`]))}
 $i('compare-run').onclick=()=>run($i('compare-run'),async(key,valid)=>{const request=++compareRequest;diffRequest++;const left=$i('compare-left').value,right=$i('compare-right').value;if(!left||!right||left===right)throw Error('Choose two different views.');$i('compare-message').textContent='Comparing the stored snapshots…';const data=await api({action:'compare',project_id:key,left_view:left,right_view:right,relations:$i('compare-relations').checked});if(!valid()||request!==compareRequest)return;comparison={left,right};summary($i('compare-summary'),[['Added in B',count(data.files.added.length)],['Missing in B',count(data.files.removed.length)],['Changed',count(data.files.changed.length)],['Renamed / identical',count(data.files.renamed.length)+' / '+count(data.unchanged)]]);$i('compare-files').innerHTML=fileButtons(data);$i('compare-message').textContent=data.notes.join(' ')+(data.analysis_partial?' Some files/relations could not be analyzed.':'');$i('compare-file-title').textContent='';$i('compare-diff').textContent='';$i('compare-graph').innerHTML=data.relations?Object.entries(data.relations).map(([kind,changes])=>'<details><summary>'+esc(kind==='calls'?'Calls':'References between files')+' · +'+changes.added_count+' / −'+changes.removed_count+'</summary><div class="insights-table-wrap">'+table(['Change','Source → target'],[...changes.added.map(x=>['Added',esc(x[0])+' → '+esc(x[1])]),...changes.removed.map(x=>['Removed',esc(x[0])+' → '+esc(x[1])])])+'</div></details>').join(''):''});
 $i('compare-files').onclick=e=>{const button=e.target.closest('[data-compare-file]');if(!button||!comparison)return;const chosen={...comparison},request=++diffRequest;run(button,async(key,valid)=>{const data=await api({action:'compare',project_id:key,left_view:chosen.left,right_view:chosen.right,file_path:button.dataset.compareFile,relations:false});if(!valid()||request!==diffRequest||comparison?.left!==chosen.left||comparison?.right!==chosen.right)return;$i('compare-file-title').textContent=button.dataset.compareFile+(button.dataset.compareFile.toLowerCase().endsWith('.docx')?' · extracted text':'');$i('compare-diff').innerHTML=data.diff_error?esc(data.diff_error):(data.diff||'The indexed text is identical; metadata/hashes may have changed.').split('\n').map(line=>'<span class="'+(line.startsWith('+')?'added':line.startsWith('-')?'removed':'')+'">'+esc(line)+'</span>').join('\n');if(data.diff_truncated)$i('compare-message').textContent+=' Diff limited to 1,000 lines / 128,000 characters.'})};
 return {reset};
})();
'''
